# Apollo 配置
app:
  id: pac-dsp
apollo:
  cluster: default
  bootstrap:
    namespaces: application,infrastructure,adm
    enabled: true
    eagerLoad:
      enabled: true
  meta: http://dev-apollo.tec-develop.com

spring:
  datasource:
    url: ${pac.datasource.dsp.url}
    username: ${pac.datasource.dsp.username}
    password: ${pac.datasource.dsp.password}