spring:
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          url: jdbc:mysql://172.24.2.26:3306/eric?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
          username: mobi
          password: mobisummer2112
        doris:
          url: jdbc:mysql://10.205.0.15:9030/ods_mb_mm?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
          username: root
          password:
  redis:
    database: 2
    host: 10.205.0.208
    password: wJgJWoVftpxjFPBV

pac:
  thread-pool:
    core-size: 128
  ctr-predict:
    url: xxx
  rta:
    url: xxx
    api: xxx
  notice:
    # 归因窗口（即回调通知有效期），单位 秒
    expire:
      win: 3600
      imp: 3600
      click: 3600
      pb: 3600