# Apollo 配置
app:
  id: pac-dsp
apollo:
  cluster: default
  bootstrap:
    namespaces: application,infrastructure,dsp
    enabled: true
    eagerLoad:
      enabled: true
  meta: http://dev-apollo.tec-develop.com

spring:
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          url: ${pac.datasource.dsp.url}
          username: ${pac.datasource.dsp.username}
          password: ${pac.datasource.dsp.password}
        doris-ods:
          url: jdbc:mysql://pacdsp-doris-external.tec-develop.com:9030/ads?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
          username: brainx
          password: JZY0oTSiONqiLdIh
        afmysql:
          url: ${pac.datasource.af.url}
          username: ${pac.datasource.af.username}
          password: ${pac.datasource.af.password}
