server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: select 1
      validation-query-timeout: 2000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

foreign:
  flat-ads:
    report-url: http://api.flat-ads.com/api/tracker/reporting/demand_report?id=${foreign.flat-ads.your-id}&apikey=${foreign.flat-ads.apikey}
    your-id: 2
    apikey: 2djsdakjeiqnvadi