# Apollo 配置
app:
  id: pac-dsp
apollo:
  cluster: default
  bootstrap:
    namespaces: application,infrastructure,job
    enabled: true
    eagerLoad:
      enabled: true
  meta: http://dev-apollo.tec-develop.com

spring:
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          url: ${pac.datasource.dsp.url}
          username: ${pac.datasource.dsp.username}
          password: ${pac.datasource.dsp.password}
        doris-ads:
          url: ${data-center.datasource.doris-ads.url}
          username: ${data-center.datasource.doris-ads.username}
          password: ${data-center.datasource.doris-ads.password}
        mysql-ddj:
          url: ${pac.datasource.ddj.url}
          username: ${pac.datasource.ddj.username}
          password: ${pac.datasource.ddj.password}
