# Apollo 配置
app:
  id: pac-dsp
apollo:
  cluster: default
  bootstrap:
    namespaces: application,infrastructure,job
    enabled: true
    eagerLoad:
      enabled: true
  meta: http://dev-apollo.tec-develop.com

spring:
  datasource:
    dynamic:
      primary: doris
      datasource:
        doris:
          url: ${data-center.datasource.doris.url}
          username: ${data-center.datasource.doris.username}
          password: ${data-center.datasource.doris.password}
